from django.test import Client, TestCase
from django.urls import reverse


class AboutViewsTests(TestCase):
    def setUp(self):
        self.guest_client = Client()
        self.urls = {
            "about/author.html": reverse("about:author"),
            "about/tech.html": reverse("about:tech"),
        }

    def test_about_pages_accessible_by_name(self):
        """URL generated by name is avialable."""
        for url in self.urls.values():
            with self.subTest(url=url):
                response = self.guest_client.get(url)
                self.assertEqual(response.status_code, 200)

    def test_about_pages_uses_correct_template(self):
        """About pages uses correct tamplate."""
        for template, url in self.urls.items():
            with self.subTest(url=url, template=template):
                response = self.guest_client.get(url)
                self.assertTemplateUsed(response, template)
